### ISSUE TITLE
Ticking Villagers

### ISSUE THREAD

**Issue by ScoutTheSaneless** [necro50n3/livelierpokemon#4]
not entirely sure what this mod is doing with villagers, but whatever it is, it's not enjoyed by the game as it makes them start ticking-

[crash-2024-02-15_15.09.20-server.txt](https://github.com/necro50n3/livelierpokemon/files/14320655/crash-2024-02-15_15.09.20-server.txt)

**Comment by CvoidWyvern** [comment]
Getting this issue as well, took forever to figure out it was this

**Comment by necro50n3** [comment]
The only thing this mod touches when it comes to villagers is making babies follow Drifloon if they are alone. I haven't been able to replicate this with just the mod itself, so can you send me your modpack to test?

**Comment by CvoidWyvern** [comment]
Do you have somewhere to send you the pack directly instead of posting it publicly?

**Comment by necro50n3** [comment]
You can DM it to me on discord @NecroSo1

**Comment by necro50n3** [comment]
Latest version of forge has solved this issue
